language: ruby
rvm:
  - 2.1.1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database myapnea_test;' -U postgres"
  - "bundle exec rake db:migrate"
